services:
  db:
    image: postgres:latest
    container_name: database_psql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: docker_learn
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql

  web:
    build: .
    container_name: server_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
      gunicorn --bind 0.0.0.0:5000 --workers 3 main:app

volumes:
  db_data:
